-- CreateTable
CREATE TABLE "studentApplication" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "hasPassport" BOOLEAN NOT NULL DEFAULT false,
    "hasCopiesOfAcademicOfHome" BOOLEAN NOT NULL DEFAULT false,
    "hasCopiesOfAcademicOfAustralia" BOOLEAN NOT NULL DEFAULT false,
    "hasCurrentCOE" BOOLEAN NOT NULL DEFAULT false,
    "hasQTEassessmentForm" BOOLEAN NOT NULL DEFAULT false,
    "hasCurriculumVitae" BOOLEAN NOT NULL DEFAULT false,
    "references" TEXT,
    "currentLocation" TEXT,
    "applicationType" TEXT,
    "title" TEXT,
    "givenName" TEXT NOT NULL,
    "middleName" TEXT,
    "familyName" TEXT NOT NULL,
    "dateOfBirth" TIMESTAMP(3),
    "emailAddress" TEXT NOT NULL,
    "mobile" TEXT,
    "homePhone" TEXT,
    "streetNumber" TEXT,
    "streetName" TEXT,
    "city" TEXT,
    "stateProvince" TEXT,
    "postalCode" TEXT,
    "country" TEXT,
    "countryOfCitizenship" TEXT,
    "passportNumber" TEXT,
    "visaNumber" TEXT,
    "ielts" TEXT,
    "dateOfTest" TIMESTAMP(3),
    "gender" TEXT,
    "countryOfBirth" TEXT,
    "cityOfBirth" TEXT,
    "austCitizenshipStatus" TEXT,
    "aboriginalOrTorresStraitIslander" TEXT,
    "employmentStatus" TEXT,
    "doSpeakEnglishAtHome" BOOLEAN,
    "requireEnglishAssisance" BOOLEAN,
    "higheshtSchoolEducation" TEXT,
    "yearCompleted" TEXT,
    "disabilities" TEXT,
    "priorEducation" TEXT,
    "alternateEmailAddress" TEXT,
    "usi" TEXT,
    "emergencyContactName" TEXT,
    "emergencyRelationship" TEXT,
    "emergencyPhonNumber" TEXT,
    "emergencyContactComments" TEXT,
    "qualificationLocation" TEXT,
    "intakeDate" TIMESTAMP(3),
    "isApplyingForCreditTransfer" BOOLEAN DEFAULT false,
    "isApplyingForRecognitionOfRPL" BOOLEAN DEFAULT false,
    "oshcType" TEXT,
    "oshcProviderName" TEXT,
    "oschMembershipNumber" TEXT,
    "oschExpiryDate" TIMESTAMP(3),
    "iCan" BOOLEAN DEFAULT false,
    "isMyFirstLang" BOOLEAN DEFAULT false,
    "canReadTimeOnClock" BOOLEAN DEFAULT false,
    "isMyFirstlang2" BOOLEAN DEFAULT false,
    "canAddUpThings" BOOLEAN DEFAULT false,
    "isMyFirstLang3" BOOLEAN DEFAULT false,
    "canKnowHowMuchChange" BOOLEAN DEFAULT false,
    "isMyFirstLang4" BOOLEAN DEFAULT false,
    "canUsePhone" BOOLEAN DEFAULT false,
    "isMyFirstLang5" BOOLEAN DEFAULT false,
    "canTakePhoneMessage" BOOLEAN DEFAULT false,
    "isMyFirstLang6" BOOLEAN DEFAULT false,
    "canFillAFormForTimesheet" BOOLEAN DEFAULT false,
    "isMyFirstLang7" BOOLEAN DEFAULT false,
    "canFollowInstructions" BOOLEAN DEFAULT false,
    "isMyFirstLang8" BOOLEAN DEFAULT false,
    "haveAttendedAUSCBefore" BOOLEAN DEFAULT false,
    "agreeToBeContacted" BOOLEAN DEFAULT false,
    "agreeTermsAndConditions" BOOLEAN DEFAULT false,
    "fullName" TEXT,
    "signature" TEXT,
    "agentName" TEXT,
    "agentEmail" TEXT,
    "businessName" TEXT,
    "studentType" TEXT,

    CONSTRAINT "studentApplication_pkey" PRIMARY KEY ("id")
);
